### ISSUE TITLE
Maps layers: Documents

### ISSUE THREAD

**Issue by VijayanB** [opensearch-project/dashboards-maps#100]
- [x] Add new layer -> Data Layer -> Documents
- [x] Data Source section
- [x] Add number of documents to fetch ( min/max/default) 
- [x] Styles section : Geopoint
- [x] Styles section : Geoshape
- [x] Settings section
- [x] Add Tool tip to Data source section
- [x] Add data Filter to Data source section
- [x] Save layer
- [x] Delete layer
