### ISSUE TITLE
Maps issues for dark mode

### ISSUE THREAD

**Issue by wbeckler** [opensearch-project/dashboards-maps#451]
- [x] (OUI Next Theme) Visualize - Region Map dashboards-maps#449
- [x] (OUI Next Theme) Visualize - Coordinate Map dashboards-maps#450
- [x] (OUI Next Theme) Maps dashboards-maps https://github.com/opensearch-project/dashboards-maps/issues/448
